### ISSUE TITLE
test_inferface causes some AX12 to go "wild"

### ISSUE THREAD

**Issue by MathieuR** [dxydas/ros-bioloid#3]
Hi Dimitris,

This might be an issue on my side but thinking you might be able to give me some pointers on the issue I am seeing.
At the first homeAllMotorsClient() call, some actuators are going to their max rotation angle (motor 3,4,7,8) causing power supply to fail.

All the 18 motors are discovered properly by the controller.

Any idea?
-Mathieu

**Comment by dxydas** [comment]
Hi Matthieu,

Are you using the latest version of the controller? In the current version,
the homing is done by essentially sending 512 via the broadcast ID to all
motors.
A while ago the controller used to add offsets to the motors as I was using
a home position that was different to the default. This offsetting has now
been removed, and all motors home to their default position (512). Please
note however that for some functions, I still include an +/- 1 inversion
factor so that the motor directions match those in my URDF.

Also note that parts of my code may be untested and in a continuous
development state as it's written mainly for my use, so I cannot hold any
responsibility if you damage your motors! Please keep this in mind and
always double-check the code!

Best of luck,
Dimitris

**Comment by MathieuR** [comment]
Hi Dimitris,

Thanks for your explanation, this matches with what I observe.
The hip default position is not at 512 in my case.

No worries, I take 100% responsibility if I damage the motors.
I tried the test app without reading the code .... :)

I will need to update the code a little bit to math my robot.

You could close this ticket if you want since the issue is on my side.

Thanks for your reply,
-Mathieu

Note:
I am unable to run the GUI on linux. It seems to be a GUI issue, maybe a QT library mismatch.

**Comment by dxydas** [comment]
Thanks for the reply. Recently I have been using QtCreator to run catkin,
as I use that as my IDE. If you want to compile the Qt GUI there will be a
few standard libs that are needed, I dont have a list of them but you might
be able to find out from the errors you are getting. Let me know how it
goes!

Regards,
Dimitris

Hi Dimitris,

Thanks for your explanation, this matches with what I observe.
The hip default position is not at 512 in my case.

No worries, I take 100% responsibility if I damage the motors.
I tried the test app without reading the code .... :)

I will need to update the code a little bit to math my robot.

You could close this ticket if you want since the issue is on my side.

Thanks for your reply,
-Mathieu

Note:
I am unable to run the GUI on linux. It seems to be a GUI issue, maybe a QT
library mismatch.

**Comment by MathieuR** [comment]
Hi Dimitris,

I am talking about the rosoloid_gui. It compile fine but the interface is not usable, it stays in background and there are alignment and border issues.

I was thinking moving some of the feature into a rqt plugin eventually unless you already that in plan.
It is a way to not worry about the gui and focus on the feature in a plugin.

But I think for me the priority is to get usb2ax_controller to work. This helps me to learn ROS and get my hands dirty.

Regards,
-Mathieu

**Comment by dxydas** [comment]
OK I see, it could be perhaps because of screen size, I have not tested it
much on other machines, but I might try in the near future.
Good luck with getting the controller working, let me know if you find
further issues!

Regards
Dimitris

**Comment by MathieuR** [comment]
Thanks,
-Mathieu
